package database;

import java.sql.*;

public class OperatorDatabase {

    public void createTable() {

        try {
            Class.forName("org.hsqldb.jdbc.JDBCDriver");
            Connection con = DriverManager.getConnection("jdbc:hsqldb:hsql://localhost/workdb", "SA","");

            String sql = "CREATE TABLE IF NOT EXISTS users (id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1) PRIMARY KEY , Username VARCHAR(30) NOT NULL, E_mail VARCHAR(50) NOT NULL, Password VARCHAR(50) NOT NULL, Premium BIT DEFAULT 0, Administrator BIT DEFAULT 0)";
            Statement stmt = con.createStatement();
            stmt.executeUpdate(sql);

        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}